# Generated by Django 5.2.17 on 2026-08-08 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.profiles.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("full_name", models.CharField(max_length=200)),
                (
                    "timezone",
                    models.CharField(max_length=64, validators=[apps.profiles.models.validate_iana_timezone]),
                ),
                ("professional_title", models.CharField(blank=True, max_length=200)),
                ("professional_summary", models.TextField(blank=True)),
                ("phone_number", models.CharField(blank=True, max_length=32)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("linkedin_url", models.URLField(blank=True)),
                ("portfolio_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["full_name"]},
        ),
    ]
