# Generated by Django 5.2.17 on 2026-08-08 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_project_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_contact_details', models.BooleanField(default=True)),
                ('show_professional_summary', models.BooleanField(default=True)),
                ('show_experience', models.BooleanField(default=True)),
                ('show_education', models.BooleanField(default=True)),
                ('show_projects', models.BooleanField(default=True)),
                ('show_skills', models.BooleanField(default=True)),
                ('show_languages', models.BooleanField(default=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_preferences', to='profiles.candidateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('normalized_name', models.CharField(editable=False, max_length=100)),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('fluent', 'Fluent'), ('native', 'Native')], max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='profiles.candidateprofile')),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'normalized_name'), name='language_unique_name_per_profile')],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('normalized_name', models.CharField(editable=False, max_length=100)),
                ('position', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='profiles.candidateprofile')),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'normalized_name'), name='skill_unique_name_per_profile')],
            },
        ),
    ]
