# Generated by Django 5.2.17 on 2026-08-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_presentationpreferences_language_skill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PresentationPreferences',
        ),
    ]
