# Generated by Django 5.2.17 on 2026-08-14 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_delete_presentationpreferences'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('normalized_label', models.CharField(editable=False, max_length=200)),
                ('position', models.PositiveIntegerField(default=0)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_skills', to='skills.skillconcept')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_skills', to='profiles.project')),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('project', 'concept'), name='project_skill_unique_concept'), models.CheckConstraint(condition=models.Q(('normalized_label', ''), _negated=True), name='project_skill_label_not_blank')],
            },
        ),
    ]
