# Generated by Django 5.2.17 on 2026-08-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_experienceskill'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='experienceskill',
            name='experience_skill_label_not_blank',
        ),
        migrations.RemoveConstraint(
            model_name='profileskill',
            name='profile_skill_label_not_blank',
        ),
        migrations.RemoveConstraint(
            model_name='projectskill',
            name='project_skill_label_not_blank',
        ),
        migrations.RemoveField(
            model_name='experienceskill',
            name='normalized_label',
        ),
        migrations.RemoveField(
            model_name='profileskill',
            name='normalized_label',
        ),
        migrations.RemoveField(
            model_name='projectskill',
            name='normalized_label',
        ),
        migrations.AddConstraint(
            model_name='experienceskill',
            constraint=models.CheckConstraint(condition=models.Q(('label', ''), _negated=True), name='experience_skill_label_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='profileskill',
            constraint=models.CheckConstraint(condition=models.Q(('label', ''), _negated=True), name='profile_skill_label_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='projectskill',
            constraint=models.CheckConstraint(condition=models.Q(('label', ''), _negated=True), name='project_skill_label_not_blank'),
        ),
    ]
