# Generated by Django 5.2.17 on 2026-08-15 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_experienceskill_experience_skill_label_not_blank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
    ]
