# Generated by Django 5.2.17 on 2026-09-13 17:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_remove_private_skill_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='revision',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
