# Generated by Django 5.2.17 on 2026-08-08 19:32

import apps.profiles.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_target', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('monthly_target', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('timezone', models.CharField(max_length=64, validators=[apps.profiles.models.validate_iana_timezone])),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('weekly_target__gt', 0)), name='campaign_weekly_target_positive'), models.CheckConstraint(condition=models.Q(('monthly_target__gt', 0)), name='campaign_monthly_target_positive'), models.CheckConstraint(condition=models.Q(('status__in', ['active', 'archived'])), name='campaign_status_valid'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('account',), name='campaign_one_active_per_account')],
            },
        ),
    ]
