# Generated by Django 5.2.17 on 2026-08-08 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_jobapplication_first_submitted_at_stagetransition'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('follow_up', 'Follow-up'), ('interview', 'Interview'), ('assessment', 'Assessment'), ('deadline', 'Deadline'), ('offer_response', 'Offer response'), ('custom', 'Custom')], max_length=20)),
                ('custom_title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=16)),
                ('scheduled_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_events', to='applications.jobapplication')),
            ],
            options={
                'ordering': ['scheduled_at', 'pk'],
            },
        ),
    ]
