# Generated by Django 5.2.17 on 2026-08-15 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_recruitmentevent'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSkillRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('normalized_label', models.CharField(editable=False, max_length=200)),
                ('classification', models.CharField(choices=[('required', 'Required'), ('preferred', 'Preferred')], max_length=16)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='applications.jobapplication')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_requirements', to='skills.skillconcept')),
            ],
            options={
                'ordering': ['classification', 'id'],
                'constraints': [models.UniqueConstraint(fields=('application', 'concept'), name='application_skill_requirement_unique_concept'), models.CheckConstraint(condition=models.Q(('normalized_label', ''), _negated=True), name='application_skill_requirement_label_not_blank'), models.CheckConstraint(condition=models.Q(('classification__in', ['required', 'preferred'])), name='application_skill_requirement_valid_classification')],
            },
        ),
    ]
