# Generated by Django 5.2.17 on 2026-08-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_applicationskillrequirement'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='applicationskillrequirement',
            name='application_skill_requirement_label_not_blank',
        ),
        migrations.RemoveField(
            model_name='applicationskillrequirement',
            name='normalized_label',
        ),
        migrations.AddConstraint(
            model_name='applicationskillrequirement',
            constraint=models.CheckConstraint(condition=models.Q(('label', ''), _negated=True), name='application_skill_requirement_label_not_blank'),
        ),
    ]
