# Generated by Django 5.2.17 on 2026-09-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_requirement_skill_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='creation_token',
            field=models.CharField(blank=True, default=None, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
