# Generated by Django 5.2.17 on 2026-09-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_jobapplication_creation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='posting_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
