# Generated by Django 5.2.17 on 2026-08-14 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(max_length=200)),
                ('canonical_key', models.CharField(editable=False, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'skill concept',
                'verbose_name_plural': 'skill concepts',
                'ordering': ['canonical_name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SkillAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
                ('normalized_value', models.CharField(editable=False, max_length=200, unique=True)),
                ('is_canonical', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='skills.skillconcept')),
            ],
            options={
                'ordering': ['normalized_value', 'pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_canonical', True)), fields=('concept',), name='skill_alias_one_canonical_per_concept')],
            },
        ),
    ]
