# Generated by Django 5.2.17 on 2026-09-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCatalogAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('alias_reassignment', 'Alias reassignment'), ('alias_deletion', 'Alias deletion')], max_length=32)),
                ('actor_id', models.BigIntegerField()),
                ('actor_email', models.CharField(max_length=254)),
                ('reason', models.TextField()),
                ('alias_id', models.BigIntegerField()),
                ('alias_display_name', models.CharField(max_length=200)),
                ('alias_normalized_value', models.CharField(max_length=200)),
                ('source_concept_id', models.BigIntegerField()),
                ('source_concept_name', models.CharField(max_length=200)),
                ('source_concept_key', models.CharField(max_length=200)),
                ('destination_concept_id', models.BigIntegerField(blank=True, null=True)),
                ('destination_concept_name', models.CharField(blank=True, max_length=200)),
                ('destination_concept_key', models.CharField(blank=True, max_length=200)),
                ('affected_application_ids', models.JSONField(default=list)),
                ('affected_requirement_ids', models.JSONField(default=list)),
                ('removed_requirement_ids', models.JSONField(default=list)),
                ('promoted_requirement_ids', models.JSONField(default=list)),
                ('kept_requirement_ids', models.JSONField(default=list)),
                ('collision_application_ids', models.JSONField(default=list)),
                ('affected_requirement_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'skill catalog audit',
                'verbose_name_plural': 'skill catalog audits',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
