# Generated by Django 5.2.17 on 2026-09-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skillcatalogaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillConceptMergeAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.BigIntegerField()),
                ('actor_email', models.CharField(max_length=254)),
                ('reason', models.TextField()),
                ('loser_concept_id', models.BigIntegerField()),
                ('loser_concept_name', models.CharField(max_length=200)),
                ('loser_concept_key', models.CharField(max_length=200)),
                ('survivor_concept_id', models.BigIntegerField()),
                ('survivor_concept_name', models.CharField(max_length=200)),
                ('survivor_concept_key', models.CharField(max_length=200)),
                ('moved_alias_ids', models.JSONField(default=list)),
                ('moved_alias_snapshots', models.JSONField(default=list)),
                ('affected_application_ids', models.JSONField(default=list)),
                ('affected_profile_skill_ids', models.JSONField(default=list)),
                ('affected_experience_skill_ids', models.JSONField(default=list)),
                ('affected_project_skill_ids', models.JSONField(default=list)),
                ('affected_requirement_ids', models.JSONField(default=list)),
                ('affected_resume_skill_ids', models.JSONField(default=list)),
                ('discarded_profile_skill_ids', models.JSONField(default=list)),
                ('discarded_experience_skill_ids', models.JSONField(default=list)),
                ('discarded_project_skill_ids', models.JSONField(default=list)),
                ('discarded_requirement_ids', models.JSONField(default=list)),
                ('discarded_resume_skill_ids', models.JSONField(default=list)),
                ('promoted_requirement_ids', models.JSONField(default=list)),
                ('collision_outcomes', models.JSONField(default=list)),
                ('affected_relationship_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'skill concept merge audit',
                'verbose_name_plural': 'skill concept merge audits',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
