# Generated by Django 5.2.17 on 2026-09-07 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIOperationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=64)),
                ('consent_policy', models.CharField(max_length=64)),
                ('outcome', models.CharField(max_length=32)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('route', models.CharField(blank=True, max_length=200)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_operation_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI operation audit',
                'verbose_name_plural': 'AI operation audits',
            },
        ),
    ]
