# Generated by Django 5.2.17 on 2026-09-07 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aioperationaudit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIOperationSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=64, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI operation switch',
                'verbose_name_plural': 'AI operation switches',
            },
        ),
        migrations.CreateModel(
            name='AIOperationReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=64)),
                ('status', models.CharField(default='in_flight', max_length=32)),
                ('reserved_cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_operation_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI operation reservation',
                'verbose_name_plural': 'AI operation reservations',
                'indexes': [models.Index(fields=['account', 'created_at'], name='ai_aioperat_account_ee0d9d_idx'), models.Index(fields=['status', 'created_at'], name='ai_aioperat_status_21b064_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'in_flight')), fields=('account',), name='unique_ai_in_flight_per_account')],
            },
        ),
    ]
