# Generated by Django 5.2.17 on 2026-09-08 00:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_aioperationswitch_aioperationreservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='aioperationaudit',
            constraint=models.CheckConstraint(condition=models.Q(('cost__gte', 0)), name='ai_audit_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='aioperationreservation',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_cost__gte', 0)), name='ai_reservation_cost_non_negative'),
        ),
    ]
