from django.urls import path

from apps.profiles.views import (
    education_create,
    education_delete,
    education_edit,
    education_reorder,
    experience_create,
    experience_delete,
    experience_edit,
    experience_reorder,
    experience_skill_create,
    experience_skill_delete,
    experience_skill_reorder,
    highlight_create,
    highlight_delete,
    highlight_edit,
    highlight_reorder,
    language_create,
    language_delete,
    language_edit,
    language_reorder,
    profile,
    project_create,
    project_delete,
    project_edit,
    project_reorder,
    project_skill_create,
    project_skill_delete,
    project_skill_reorder,
    skill_create,
    skill_delete,
    skill_reorder,
)

urlpatterns = [
    path("profile/", profile, name="profile"),
    path("profile/experience/new/", experience_create, name="experience_create"),
    path(
        "profile/experience/<int:experience_id>/edit/",
        experience_edit,
        name="experience_edit",
    ),
    path(
        "profile/experience/<int:experience_id>/delete/",
        experience_delete,
        name="experience_delete",
    ),
    path(
        "profile/experience/<int:experience_id>/reorder/",
        experience_reorder,
        name="experience_reorder",
    ),
    path(
        "profile/experiences/<int:experience_id>/skills/new/",
        experience_skill_create,
        name="experience_skill_create",
    ),
    path(
        "profile/experience-skills/<int:experience_skill_id>/delete/",
        experience_skill_delete,
        name="experience_skill_delete",
    ),
    path(
        "profile/experience-skills/<int:experience_skill_id>/reorder/",
        experience_skill_reorder,
        name="experience_skill_reorder",
    ),
    path("profile/education/new/", education_create, name="education_create"),
    path(
        "profile/education/<int:education_id>/edit/",
        education_edit,
        name="education_edit",
    ),
    path(
        "profile/education/<int:education_id>/delete/",
        education_delete,
        name="education_delete",
    ),
    path(
        "profile/education/<int:education_id>/reorder/",
        education_reorder,
        name="education_reorder",
    ),
    path(
        "profile/experience/<int:experience_id>/highlights/new/",
        highlight_create,
        name="highlight_create",
    ),
    path(
        "profile/experience/<int:experience_id>/highlights/<int:highlight_id>/edit/",
        highlight_edit,
        name="highlight_edit",
    ),
    path(
        "profile/experience/<int:experience_id>/highlights/<int:highlight_id>/delete/",
        highlight_delete,
        name="highlight_delete",
    ),
    path(
        "profile/experience/<int:experience_id>/highlights/<int:highlight_id>/reorder/",
        highlight_reorder,
        name="highlight_reorder",
    ),
    path("profile/projects/new/", project_create, name="project_create"),
    path(
        "profile/projects/<int:project_id>/edit/",
        project_edit,
        name="project_edit",
    ),
    path(
        "profile/projects/<int:project_id>/delete/",
        project_delete,
        name="project_delete",
    ),
    path(
        "profile/projects/<int:project_id>/reorder/",
        project_reorder,
        name="project_reorder",
    ),
    path(
        "profile/projects/<int:project_id>/skills/new/",
        project_skill_create,
        name="project_skill_create",
    ),
    path(
        "profile/project-skills/<int:project_skill_id>/delete/",
        project_skill_delete,
        name="project_skill_delete",
    ),
    path(
        "profile/project-skills/<int:project_skill_id>/reorder/",
        project_skill_reorder,
        name="project_skill_reorder",
    ),
    path("profile/skills/new/", skill_create, name="skill_create"),
    path("profile/skills/<int:skill_id>/delete/", skill_delete, name="skill_delete"),
    path("profile/skills/<int:skill_id>/reorder/", skill_reorder, name="skill_reorder"),
    path("profile/languages/new/", language_create, name="language_create"),
    path("profile/languages/<int:language_id>/edit/", language_edit, name="language_edit"),
    path("profile/languages/<int:language_id>/delete/", language_delete, name="language_delete"),
    path(
        "profile/languages/<int:language_id>/reorder/",
        language_reorder,
        name="language_reorder",
    ),
]
